# **1. Conectar Google Drive a Colab (Mounting)**

Como regla indispensable para trabajar con archivos locales, iniciamos preparando nuestro entorno:
* `from google.colab import drive`: Llamamos a la herramienta de conexión.
* `drive.mount('/content/drive')`: Le damos permiso a Colab para acceder a nuestras carpetas y buscar el archivo de Excel.

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **2. Cargar y visualizar los datos**

Importamos nuestra librería de análisis y abrimos el archivo de la NBA:
* `import pandas as pd`: Llamamos a Pandas.
* `read_excel()`: Cargamos el archivo usando la ruta exacta de la nube.
* `.head()`: Imprimimos las primeras 5 filas para verificar que todo cargó correctamente.

In [4]:
import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/aplicada/Nba Teams.xlsx')
nba.head()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH

# **3. Ordenar datos alfabéticamente**

Podemos organizar los registros basándonos en columnas de texto:
* `.sort_values("Name")`: Toma la columna de nombres y reorganiza toda la tabla de la A a la Z.
* `.head(20)`: Como una tabla de la NBA puede ser muy larga, encadenamos este método al final para ver únicamente los primeros 20 resultados de nuestro listado ya ordenado.

In [5]:
nba.sort_values("Name").head(20)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
354,Aaron Gordon,Orlando Magic,SouthEast,F,6'8,235.0,1995-09-16,Arizona,18136364.0,US
186,Aaron Holiday,Indiana Pacers,Central,G,NaN,185.0,1996-09-30,UCLA,2345640.0,US
18,Aaron Nesmith,Boston Celtics,Atlantic,G-F,6'6,213.0,1999-10-16,Vanderbilt,3458400.0,US
388,Abdel Nader,Phoenix Suns,Pacific,F,6'5,225.0,1993-09-25,"Northern Illinois, Iowa State",1752950.0,EG
70,Adam Mokoka,Chicago Bulls,Central,G,6'5,190.0,1998-07-18,NaN,NaN,FR
337,Al Horford,Oklahoma City Thunder,NorthWest,C-F,6'9,240.0,1986-06-03,Florida,27500000.0,DO
355,Al-Farouq Aminu,Orlando Magic,SouthEast,F,6'8,220.0,1990-09-21,Wake Forest,9720900.0,US
319,Alec Burks,New York Knicks,Atlantic,G,6'6,214.0,1991-07-20,Colorado,6000000.0,US
338,Aleksej Pokusevski,Oklahoma City Thunder,NorthWest,F,6'11,215.0,2001-12-26,NaN,2964840.0,RS
219,Alex Caruso,Los Angeles Lakers,Pacific,G,6'5,186.0,1994-02-28,Texas A&M,2750000.0,US
449,Alex Len,Toronto Raptors,Atlantic,C,7'0,250.0,1993-06-16,Maryland,2320000.0,UA
220,Alfonzo McKinnie,Los Angeles Lakers,Pacific,F,6'7,215.0,1992-09-17,Green Bay,1762796.0,US
85,Andre Drummond,Cleveland Cavaliers,Central,C,6'10,279.0,1993-08-10,UConn,28751775.0,US
251,Andre Iguodala,Miami Heat,SouthEast,G-F,6'6,215.0,1984-01-28,Arizona,15000000.0,US
153,Andrew Wiggins,Golden State Warriors,Pacific,F-G,6'7,197.0,1995-02-23,Kansas,29542010.0,CA
403,Anfernee Simons,Portland Trail Blazers,NorthWest,G,6'3,181.0,1999-06-08,NaN,2252040.0,US
221,Anthony Davis,Los Angeles Lakers,Pacific,F-C,6'10,253.0,1993-03-11,Kentucky,32742000.0,US
286,Anthony Edwards,Minnesota Timberwolves,NorthWest,G,6'5,225.0,2001-08-05,Georgia,9757440.0,US
481,Anthony Gill,Washington Wizards,SouthEast,F,6'8,230.0,1992-10-17,"South Carolina, Virginia",898310.0,US
450,Aron Baynes,Toronto Raptors,Atlantic,C,6'10,260.0,1986-12-09,Washington State,6975610.0,NZ

# **4. Orden numérico y parámetros de control**

Podemos aplicar el mismo principio a columnas numéricas, como los salarios:
* `sort_values("Salary")`: Por defecto, Pandas siempre organiza los números de menor a ascendente (de menor a mayor).
* `#nba.sort_values(..., ascending = False, inplace = True)`: El código inactivo nos muestra una combinación muy potente. Si cambiamos `ascending` a `Falso`, la tabla se ordena de **mayor a menor** (ideal para ver los salarios más altos primero), y el `inplace = True` guardaría ese orden permanentemente en la memoria.

In [6]:
nba.sort_values("Salary")
#nba.sort_values("Salary", ascending = False, inplace = True)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
225,Kostas Antetokounmpo,Los Angeles Lakers,Pacific,F,6'10,200.0,1997-11-20,Dayton,280000.0,GR
254,Breein Tyree,Miami Heat,SouthEast,G,6'2,195.0,1998-01-13,Ole Miss,280000.0,US
248,Sean McDermott,Memphis Grizzlies,SouthWest,F,6'6,195.0,1996-11-03,Butler,280000.0,US
222,Dennis Schroder,Los Angeles Lakers,Pacific,G,6'1,172.0,1993-09-15,NaN,280000.0,DE
245,Killian Tillie,Memphis Grizzlies,SouthWest,F,6'10,220.0,1998-03-05,Gonzaga,380000.0,FR
...,...,...,...,...,...,...,...,...,...,...
479,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
483,Cassius Winston,Washington Wizards,SouthEast,G,6'1,205.0,1998-02-28,Michigan State,NaN,US
486,Garrison Mathews,Washington Wizards,SouthEast,G,6'5,215.0,1996-10-24,Lipscomb,NaN,US
489,Jerome Robinson,Washington Wizards,SouthEast,G,6'4,190.0,1997-02-22,Boston College,NaN,US
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

# **5. Orden jerárquico (Múltiples columnas) y control de nulo**s

A veces necesitamos organizar la información usando más de un criterio a la vez:
* `["Team", "Name"]`: Al pasar una lista con varias columnas, Pandas ordena primero por equipo. Si encuentra jugadores en el mismo equipo, los ordena alfabéticamente por su nombre (como una jerarquía de orden).
* `#na_position = 'first'`: El código comentado nos enseña un truco avanzado. Por defecto, los datos vacíos (`NaN`) se van al final de la tabla; este parámetro nos permite decidir si queremos que los huecos aparezcan obligatoriamente al principio (`'first'`).

In [7]:
nba.sort_values(["Team", "Name"])
#nba.sort_values(["Team", "Name"], na_position = 'first')

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
291,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
322,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
369,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
479,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

# **6. Resumen del proceso completo**

En conclusión, este archivo nos enseña el control total sobre la organización y jerarquía de nuestras tablas:
* **Ordenamiento flexible:** Aprendimos a usar `.sort_values()` para estructurar datos tanto alfabética como numéricamente de manera instantánea.
* **Dirección de los datos:** Comprendimos cómo manipular la dirección del orden usando el parámetro `ascending = False` para destacar los valores máximos (como salarios altos).
* **Jerarquías y excepciones:** Descubrimos que podemos ordenar por varias columnas simultáneamente pasando una lista de Python, y controlar el comportamiento de los datos faltantes mediante el parámetro `na_position`.